title: Segment
description: ""
baseurl: "/docsv2" # the subpath of your site, e.g. /blog
url: "http://0.0.0.0:4000" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
plugins:
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - vendor/bundle/
  - vendor/cache/
  - Gemfile
  - Gemfile.lock
  - Makefile
  - Dockerfile
  - README.md
  - conf/
