###
### Display
###
# Verbose program output
verbose = false

# Show progress
progress = true


###
### Runtime
###
# Number of threads to utilize.
# Defaults to number of cores available to the system if omitted.
#threads = 2

# Maximum number of allowed redirects
max_redirects = 10


###
### Requests
###
# User agent to send with each request
user_agent = "lychee/0.8.0"

# Website timeout from connect to response finished
timeout = 30

# Comma-separated list of accepted status codes for valid links.
# Omit to accept all response types.
#accept = "text/html"

# Proceed for server connections considered insecure (invalid TLS)
insecure = false

# Only test links with the given scheme (e.g. https)
# Omit to check links with any scheme
scheme = ['https', 'http']

# Request method
method = "get"

# Custom request headers
headers = []


###
### Exclusions
###
# Exclude URLs from checking (supports regex)
exclude = ['https://segment.zendesk.com','(example-service)','(redacted)','(foo)','http://dl.bintray.com/swrve-inc/android','https://ajs.cd.segment.com/analytics.js/v1/','http://0.0.0.0:4000','https://api.segment.io/v1/', 'https://segment.com/docs/assets/docs.bundle.js','https://www.linkedin.com', 'https://segment.com/jobs/', 'https://segment.com/press/', 'https://github.com/segmentio', 'https://unpkg.com/@segment/consent-manager@4.2.2/standalone/consent-manager.js', '(segment.com)', '(segmentapis.com)', '(example.com)', '(schema.org)','(maxcdn)', '(your-org-name)', '(mywebsite)']

# Exclude URLs contained in a file from checking
exclude_file = []

include = []

# Exclude all private IPs from checking
# Equivalent to setting `exclude_private`, `exclude_link_local`, and `exclude_loopback` to true
exclude_all_private = true

# Exclude private IP address ranges from checking
exclude_private = false

# Exclude link-local IP address range from checking
exclude_link_local = true

# Exclude loopback IP address range and localhost from checking
exclude_loopback = false

# Exclude all mail addresses from checking
exclude_mail = true