version: 2
jobs:
  build:
    working_directory: ~/segment-docs
    docker:
      - image: 528451384384.dkr.ecr.us-west-2.amazonaws.com/node-helpers:v8.11.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build static site
          command: |
            make build
      - run:
          name: Publish to Trebuchet
          environment:
            ECR_REPOSITORY_NAME: segment-docs
          command: |
            curl -sLu "$GH_LOGIN:" https://raw.githubusercontent.com/segmentio/scripts/master/circle/trebuchet.sh | bash

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: segmentio-org-global