version: 2
jobs:
  build:
    machine: true
    working_directory: ~/segment-docs
    steps:
      - checkout

      - run:
          name: Build static site
          command: |
            make build

      - run:
          name: Publish to Trebuchet
          environment:
            ECR_REPOSITORY_NAME: segment-docs
          command: |
            # curl -sLu "$GH_LOGIN:" https://raw.githubusercontent.com/segmentio/scripts/master/circle/trebuchet.sh | bash

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: segmentio-org-global