version: 2
jobs:
  build:
    working_directory: /go/src/github.com/segmentio/segment-docs
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run:
          name: Build static site
          command: |
            make build

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: segmentio-org-global
