# This is a basic workflow to help you get started with Actions

name: CheckLinks
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checklinks:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Build jekyll website
        run: bundle exec jekyll build
      # - name: Check for broken links
      #   uses: lycheeverse/lychee-action@v1.0.8
      #   with:
      #     args: -v -n ./_site/utils/env/index.html
      #   env: 
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      # - name: Create Issue From File
      #   uses: peter-evans/create-issue-from-file@v3
      #   with:
      #     title: Link Checker Report
      #     content-filepath: ./lychee/out.md
      #     labels: report, automated issue
      - name: My Broken Link Checker
        uses: ruzickap/action-my-broken-link-checker@v1.0.3
        with:
          url: https://segment.com/docs
          pages_path: ./_site/utils/env/index.html
          cmd_params: "--skip-tls-verification --verbose --color=always"
          run_timeout: 10
          debug: true 
