name: CheckLinks

# **What it does**: Runs a weekly check for broken internal links.
# **Why we have it**: We want to make sure that pages we link to work.
# **Who does it impact**: Everyone



on:
  schedule:
    - cron: "5 4 * * SAT"

jobs:
  checklinks:
    if: github.repository == 'segmentio/segment-docs'
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Yarn install
        run: yarn install
      - name: Build jekyll website with
        run: bundle exec jekyll build
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.1.0
        with:
          args: --no-progress _site/**/*.html -a 429 -c ./lychee.toml
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      # - name: "exclude non-400 errors"
      #   run: |
      #     sudo grep -v "error sending request" ./lychee/out.md > ./lychee/out2.md
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
