name: Merged notification

# **What it does**: When we merge an open-source pull request, we want to set expectations that deployment may take awhile.
# **Why we have it**: Merged PRs go into a queue, not straight to build.
# **Who does it impact**: Open-source contributors.

on:
  pull_request_target:
    types:
      - 'closed'

jobs:
  comment:
    if: github.repository == 'segmentio/segment-docs' && github.event.pull_request.merged && github.event.pull_request.base.ref == github.event.repository.default_branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@2b34a689ec86a68d8ab9478298f91d5401337b7d
        with:
          script: |
            github.issues.createComment({
              ...context.repo,
              issue_number: context.payload.pull_request.number,
              body: "Thank you for your contribution! Your pull request is merged, but may take a day or two to appear on the site."
            })